name: Update Version

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'deno.json'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      
      - name: Update Version
        run: |
          # Version auslesen
          CURRENT_VERSION=$(deno eval "console.log(JSON.parse(Deno.readTextFileSync('./deno.json')).version)")
          
          # Version inkrementieren (hier Patch-Version)
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          NEW_PATCH=$((VERSION_PARTS[2] + 1))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH"
          
          # JSON aktualisieren
          deno eval "const json = JSON.parse(Deno.readTextFileSync('./deno.json')); json.version = '$NEW_VERSION'; Deno.writeTextFileSync('./deno.json', JSON.stringify(json, null, 2));"
          
          echo "Version updated from $CURRENT_VERSION to $NEW_VERSION"
      
      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add deno.json
          git commit -m "chore: bump version to $(deno eval "console.log(JSON.parse(Deno.readTextFileSync('./deno.json')).version)")"
          git push